# Dependencies
highlighter:      rouge

markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge
# filter used to process markdown. note that kramdown differs from github-flavored markdown in some subtle ways


# Permalinks
permalink:        pretty

# Setup
title:            RAPPS
tagline:          'Research Applications'
description:      'Research Applications'
url:              https://researchapps.github.io
baseurl:          /

author:
  name:           'Vanessa Sochat'
  url:            https://twitter.com/vsoch

paginate:         5
gems: [jekyll-paginate, jekyll-gist]
collections:
- docs

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"


# Stuff to ignore
exclude:
- playground
- _drafts

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/researchapps/researchapps.github.io


# Social networking, etc
google_analtics: "UA-85750967-1"
disqus_shortname: "stanfordrc"
twitter_username: StanfordCompute
github_username: researchapps
